Numpy is the fundamentale package for numeric computing with python. it provides powerful ways to create, store, and/or manipulate data,which makes it able to seamlessly and speedly integrate with a wide variety of databases. this is also the foundation that pandas is built on. Which is a high-performance data-centric package

**We will talk about creating array with certain data typpes, manipulating array,selecting elements from arrays, and loading  dataset into array Such functions are useful for manipulating data and understanding the functionalities of other common data packages**

In [10]:
# we import a library using the 'import' keyword as numpy's common abbreviation is np

import numpy as np
import math

## **Array creation** ##

In [11]:
# Array are displayed as list of lists and can be created through list as well. 
# when creationg an array, we pass in a list as an argument in numpy array

a = np.array([1,2,3])
print(a)
# we can print the number of dimensions of list using the ndim attribute
print(a.ndim)

[1 2 3]
1


In [12]:
# if we pass in list of lists in numpy array, we create a multi-dimensional array, 
# for instance, a matrix

b = np.array([[7,9,6],[2,5,8]])
b


array([[7, 9, 6],
       [2, 5, 8]])

In [13]:
# we can also print out the length of each dimension by calling the shape attribute,
# which return a tuble

b.shape

(2, 3)

In [14]:
# we can also check the type of items in the array
a.dtype

dtype('int32')

In [15]:
b.dtype

dtype('int32')

In [16]:
# let create two arrays, both the same shape but with different filler values

d = np.zeros((2,3))
print(d)

e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
# we can also generate an array with random numbers
np.random.rand(2,3)

array([[0.70371479, 0.07143526, 0.01187388],
       [0.08762174, 0.74947672, 0.66689075]])

In [18]:
# you'll see zeros, ones,and rand used quite often to create example arrays
# especially in stack overflow posts and other forums. 

In [19]:
# let's creat an array of every even number from ten (inclusive) to fifty (exclusive)
f = np.arange(10,50,2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [20]:
# if we want to generate a sequence of floats, we can use linspace() function. 
# In this function the third argument 1 

np.linspace(0,2,15) # 15 numbers from 0 (inclusive) to 2 (inclusive)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

## Array Operations ##

In [21]:
# we can do many things on arrays, such as mathematical (addition,substraction, square)
# as well as use boolean arrays, which are binary  values. we can also do matrix 
# manipulation such as pruduct, transpose, inverse, and so forth.

In [22]:
# arithmethic operators on array apply elementwise.
# let's creat a couple of arrays
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

# now let look at a minus b 
c = a-b
print(c)

# and let's look at a time b
d = a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [23]:
# with arithmetic manipulation, we can convert current data to the way we want it to be.
# here is the real word problem we face. in canada we use celsius for temperatures, and my wife 
# still hasn't convert to the US system which uses farenheit. with numpy
# i could easily convert a number of farenheit values, say the weather forecase, to celcius

# Let's create an array of typical Ann Arbor winter farenheit values
farenheit = np.array([0,-5,-15,0])

# and the formula for conversion is ((F - 32)*5/9) = C
celcius = (farenheit-32)/(5/9)
celcius

array([-57.6, -66.6, -84.6, -57.6])

In [24]:
# another useful and important manipulation is the bolean array. we can apply an operation
# on an array, and a boolean array will be returned for any element in the original,
# with true being emitted if it meets the condition for instance, if we want to get a boolean
# array to check celsius degrees that are greater than - 20 degree

celcius > -57.6

array([ True, False, False,  True])

In [25]:
# brsides elements manipulation, it is important to know that numpy supports matrix manipulation.
# let's look at matrix product. if we want to do elementwise product, we use the "*" sign

A = np.array([[1,1],[0,1]]) 
B = np.array ([[2,0],[3,4]])
print(A*B)

# if we want to do matrix produc, we use the "@" sign or use the dot function
print(A@B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [26]:
# a few more linear algebra concepts are worth layering in here. you might recall 
# that the product of two matrices is only possible when the inner dimensions of the 
# two matrices are the same. the dimensions refer to the number of elements both 
# horizontal and vertical in the rendered matricies, we can use numpy to quickly see
# the shape of a matrix:
A.shape

(2, 2)

In [27]:
# when manipulating arrays of different types, the type of the resulting array correspond
# to the more general of the two types. this is called upcasting.

# let's create an array of integers
array1 = np.array([[1,2,3],[4,5,6]])
print(array1.dtype)

# now let's creat an array of floats
array2 = np.array([[7.1,8.2,9.1],[10.4,11.2,12.3]])
print(array2.dtype)

int32
float64


In [28]:
# intergers (int) are whole numbers only, and floating point numbers(float) can have 
# a whole number portion and a decimal portion. the 64 in this example refers to the 
# number of bits that the operating system is reserving to represent the number,
# which determines the sizes (or precision) of the numbers that can be represent

In [29]:
# let's do an addition for the two arrays
array3 = array1 + array2
print(array3)
print(array3.dtype)

[[ 8.1 10.2 12.1]
 [14.4 16.2 18.3]]
float64


In [30]:
# notice how the items in the resulting array have been upcast in floating point numbers

In [31]:
# numpy arrays have may interesting aggregation functions on them, such as
# sum(), max(), min(), and mean()
print(array3.sum())
print(array3.max())
print(array3.min())
print(array3.mean())

79.3
18.3
8.1
13.216666666666667


In [32]:
# for two dimensional array, we can do the same thing for each row or column
# let's creat an array with 15 elements, ranging from 1 to 15
# with a dimension of 3*5
b = np.arange(1,16,1).reshape(3,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [33]:
# now , we often think about two dimensional arrays, being made up of rows and columns,
# but you can also think of these arrays as just a giant ordered list of numbers, and the 
# *shape* of the array, the number of rows and colums, is just an abstraction that we have 
# for a particular purpose. Actually, this is exactly how 

# let's take a look at an example and see how numpy comes into play.

## Indexing, Slicing and Iterating ##

In [34]:
# indexing ,slicing and iterating are extremely import for data manipulation and analyse
# because these techniques allow us to select data based on conditions, and copy or update data

**Indexing**

In [35]:
# first we are going to look at indexing, a one-dimensional array, works in similar 
# ways as a list to get an element in a one-dimensional array, we simply use the offset index

a = np.array([1,3,5,7])
a

array([1, 3, 5, 7])

In [36]:
# for multidimensional array, we need to use integer array indexing, let's creat a 
# new multidimensional array
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
# if we want to select one certain element, we can do so by entering the index, which
# is comprised of two intergers the first being the row, and the second the column

a[1,1] # remember in python we start at 0!

4

In [38]:
# if we want to get multiple elements for example, 1,4 amd 6 and put them into a 
# one-dimensional array we can enter the indices directly into an array function
np.array([a[0,0],a[1,1],a[2,1]])

array([1, 4, 6])

In [39]:
# we can also do that by using another form of array indexing, which essentiall"zips"
# the first and thesecond list up
print(a[[0,1,2], [0,1,1]])

[1 4 6]


## Boolean Indexing ##

In [40]:
# Boolean indexing allows us to select arbitrary elements based on conditions
# for example, in the matrix we just talked about we want to find elements that are greater
# than 5 so we set up a condition a>5
print(a>5)
# this returns a boolean array showing that if the value at the corresponding index is greater than 5

[[False False]
 [False False]
 [False  True]]


In [41]:
# we can then place this array of booleans like a mask over the original array to return
# a one-dimensional array relating to the true values
print(a[a>5])

[6]


## *Slicing* ##

In [42]:
# slicing is away to creat a sub-array based on the original array. For one-dimensional
# array, slicing work in similar ways to a list. To slice, we use the ":" sign. for instance
# if we put:3 in the indexing brackets, we get elements from index 0 to index 3 (excluding index 3)
a = np.array([0,1,2,3,4,5])
print(a[:3])


[0 1 2]


In [43]:
# by putting 2:4 in the bracket, we get elements from index 2 to index 4(excluding index 4)
print(a[2:4])

[2 3]


In [44]:
# for multi-dimensional arrays, it works similary, lets see an example
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
# first, if we put one argument in the aray, for example a[:2] them we would get all the
# elements from the first (0th) and second row (1th)
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
# if we add another argument to the array, for example a[:2,1:3], we get the firt two
# rows but then the second and third column values only
a[:2,1:3]

array([[2, 3],
       [6, 7]])

In [47]:
# so, in multidimensional arrays, the first argument is for selecting rows, and the second argument is
# for selecting

In [48]:
# it is important to realize that a slice of an array is a view into the same data. This is
# called passing by refernce. so modifying the sub array will consequently modify the original array
# Here i will change the element at position [0,0], which is 2, to 50, then we can see 
# the value in the original array is changed to 50 as well

sub_array = a[:2,1:3]
print("sub array index [0,0] value before change:", sub_array[0,0])
sub_array[0,0] = 50
print("sub array index [0,0] value after change:", sub_array[0,0])
print("original array index[0,1] value after change:", a[0,1])

sub array index [0,0] value before change: 2
sub array index [0,0] value after change: 50
original array index[0,1] value after change: 50
